# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'

target 'Surplus' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Surplus
  pod 'Firebase/Core'

  target 'SurplusTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Surplus-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Surplus-tvOS

  target 'Surplus-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
